### ISSUE TITLE
Propose stackoverflow badges project alternative

### ISSUE THREAD

**Issue by johannchopin** [rzashakeri/beautify-github-profile#12]
Hey @rzashakeri 👋 Thanks for the work put into this project.

I came across this one by chance and saw that you were proposing to use the [stackoverflow-badge](https://github.com/claytonjhamilton/stackoverflow-badge) which is really nice. 

I had also done a project of this kind called  [stackoverflow-readme-profile](https://github.com/johannchopin/stackoverflow-readme-profile) which offers more customisation, animations and the display of the person's avatar just like:

[![johannchopin's SO profile](https://stackoverflow-readme-profile.johannchopin.fr/profile/8583669?theme=dark)](https://github.com/johannchopin/stackoverflow-readme-profile)

[![johannchopin's SO profile](https://stackoverflow-readme-profile.johannchopin.fr/profile-small/8583669?theme=dark)](https://github.com/johannchopin/stackoverflow-readme-profile)

So I suggest you generate your own using the generator at https://johannchopin.github.io/stackoverflow-readme-profile and if you like the project would it be possible to mention it as a badge idea for stackoverflow?

**Comment by rzashakeri** [comment]
> Hey @rzashakeri 👋 Thanks for the work put into this project.
> 
> I came across this one by chance and saw that you were proposing to use the [stackoverflow-badge](https://github.com/claytonjhamilton/stackoverflow-badge) which is really nice.
> 
> I had also done a project of this kind called [stackoverflow-readme-profile](https://github.com/johannchopin/stackoverflow-readme-profile) which offers more customisation, animations and the display of the person's avatar just like:
> 
> [![johannchopin's SO profile](https://camo.githubusercontent.com/749544b315ee18b5cb8662feaa076ddef1af87a49f1f0f995c58fe911c351a04/68747470733a2f2f737461636b6f766572666c6f772d726561646d652d70726f66696c652e6a6f68616e6e63686f70696e2e66722f70726f66696c652f383538333636393f7468656d653d6461726b)](https://github.com/johannchopin/stackoverflow-readme-profile)
> 
> [![johannchopin's SO profile](https://camo.githubusercontent.com/45f30009b9d736628b9de506862a112767b9149548fd07fdea5f496be723b21f/68747470733a2f2f737461636b6f766572666c6f772d726561646d652d70726f66696c652e6a6f68616e6e63686f70696e2e66722f70726f66696c652d736d616c6c2f383538333636393f7468656d653d6461726b)](https://github.com/johannchopin/stackoverflow-readme-profile)
> 
> So I suggest you generate your own using the generator at https://johannchopin.github.io/stackoverflow-readme-profile and if you like the project would it be possible to mention it as a badge idea for stackoverflow?

Hello my friend @johannchopin 🖐️
Thanks for sharing this tool 🙏
The tool is great and I added it to the list 💙
