### ISSUE TITLE
Open AI Activity Summaries

### ISSUE THREAD

**Issue by OR13** [rzashakeri/beautify-github-profile#13]
**Is your feature request related to a problem? Please describe.**

I wanted to generate a text summary of my recent activity using GPT-3 / Open AI, and have my profile automatically updated.

**Describe the solution you'd like**

I built this kinda hacky solution here: https://github.com/OR13/OR13/blob/main/.github/workflows/weekly.yml

Here is an example of the revisions it publishes weekly: https://github.com/OR13/OR13/commit/bbc7674e401f640f6099cadfbd5dc018fd6f96f1

I would welcome any feedback on it / for it to be supported by a team /  group with more time.

**Describe alternatives you've considered**

I think many of the examples in this repo are good alternatives, especially the ones summarizing activity.

**Additional context**

This is kinda just an FYI that this is possible, I'm happy to collaborate on it if folks are interested, but I'm also happy to just have it closed.

**Comment by rzashakeri** [comment]
Hello my friend
You made a very good tool, whenever you like, tell me to add it to the list of this repository for everyone to use 👌

**Comment by rzashakeri** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I wanted to generate a text summary of my recent activity using GPT-3 / Open AI, and have my profile automatically updated.
> 
> **Describe the solution you'd like**
> 
> I built this kinda hacky solution here: https://github.com/OR13/OR13/blob/main/.github/workflows/weekly.yml
> 
> Here is an example of the revisions it publishes weekly: [OR13/OR13@bbc7674](https://github.com/OR13/OR13/commit/bbc7674e401f640f6099cadfbd5dc018fd6f96f1)
> 
> I would welcome any feedback on it / for it to be supported by a team / group with more time.
> 
> **Describe alternatives you've considered**
> 
> I think many of the examples in this repo are good alternatives, especially the ones summarizing activity.
> 
> **Additional context**
> 
> This is kinda just an FYI that this is possible, I'm happy to collaborate on it if folks are interested, but I'm also happy to just have it closed.

Hello my friend
You made a very good tool, whenever you like, tell me to add it to the list of this repository for everyone to use 👌
