### ISSUE TITLE
Duplicate widget anchor

### ISSUE THREAD

**Issue by kashan-ahmad** [rzashakeri/beautify-github-profile#2]
[README.md] Widget #12, named `Blog Post Workflow` has the anchor of the previous widget.

[README.md] Requesting a fix of the anchor.

**Comment by rzashakeri** [comment]
> [README.md] Widget #12, named `Blog Post Workflow` has the anchor of the previous widget.
> 
> [README.md] Requesting a fix of the anchor.

Thank you for saying that
Checked and I fixed it 💙
