### ISSUE TITLE
Add: New Resource

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rzashakeri/beautify-github-profile#25]
It is not a feature!!

I just wanted to add a resource and let me know if it is under the guidelines of this repository.

Visit the link [here](https://github.com/Anmol-Baranwal/Cool-GIFs-For-Readme) for curated list of GIFs & Avatars for GitHub.

I didn't want to make a PR without confirming.

@rzashakeri 
Please assign me this issue if I can add this gif repo link.

**Comment by rzashakeri** [comment]
> It is not a feature!!
> 
> I just wanted to add a resource and let me know if it is under the guidelines of this repository.
> 
> Visit the link [here](https://github.com/Anmol-Baranwal/Cool-GIFs-For-Readme) for curated list of GIFs & Avatars for GitHub.
> 
> I didn't want to make a PR without confirming.
> 
> @rzashakeri 
> Please assign me this issue if I can add this gif repo link.

Hello, it is a very good repository, you can add at least two of the gifs that you think are the best as examples, because if you want to add them all, the page will be too heavy. 💙

**Comment by Anmol-Baranwal** [comment]
Okay, I will make the changes. 

Of course, I was not going to add all the GIFs.

**Comment by rzashakeri** [comment]
> Okay, I will make the changes. 
> 
> Of course, I was not going to add all the GIFs. 

Thanks 💙🙏
