### ISSUE TITLE
GitHub Readme Quotes not working anymore

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rzashakeri/beautify-github-profile#27]
[GitHub Readme Quotes](https://github.com/rzashakeri/beautify-github-profile#39-github-readme-quotes) is not working anymore.

- I think, resources which are not working needs to be updated, so I thought to let you know.

**Comment by rzashakeri** [comment]
> [GitHub Readme Quotes](https://github.com/rzashakeri/beautify-github-profile#39-github-readme-quotes) is not working anymore.
> 
>     * I think, resources which are not working needs to be updated, so I thought to let you know.

Thank you for your offer, we will eliminate inactive tools
Checked as if the reason is that
https://github.com/shravan20/github-readme-quotees/issues/156#SISCOMMENT-117956442
