### ISSUE TITLE
Broken link for Peerlist

### ISSUE THREAD

**Issue by 0xMimir** [rzashakeri/beautify-github-profile#37]
**Describe the bug**
Broken link for example for Peerlist, broken link is [https://peerlist-readme-badge.herokuapp.com/api/vinitshahdeo](https://peerlist-readme-badge.herokuapp.com/api/vinitshahdeo)

**To Reproduce**
1. Go to `README.md`
3. Scroll down to `Peerlist`

**Expected behavior**
Show the peerlist widget

**Screenshots**
<img width="554" alt="image" src="https://github.com/rzashakeri/beautify-github-profile/assets/108837858/b996bb33-197b-4177-a61d-334330c6b1c7">

**Comment by rzashakeri** [comment]
> **Describe the bug** Broken link for example for Peerlist, broken link is https://peerlist-readme-badge.herokuapp.com/api/vinitshahdeo
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to `README.md`
> 
>     2. Scroll down to `Peerlist`
> 
>     3. See error
> 
> 
> **Expected behavior** Show the peerlist widget
> 
> **Screenshots** <img alt="image" width="554" src="https://user-images.githubusercontent.com/108837858/273600729-b996bb33-197b-4177-a61d-334330c6b1c7.png">

Thanks for reporting 
fixed
