### ISSUE TITLE
Broken link for leetcode Stats

### ISSUE THREAD

**Issue by 0xMimir** [rzashakeri/beautify-github-profile#38]
**Describe the bug**
Image for leetcode stats
```md
<img alt="LeetCode Stat Card" src="https://camo.githubusercontent.com/1eebccd44222e88e734e4b4972493af998af8fa27f2008244f3e9b90f85497d4/68747470733a2f2f6170753572683867786b2e657865637574652d6170692e75732d656173742d312e616d617a6f6e6177732e636f6d2f64656661756c742f6c656574636f64652d73746174733f757365726e616d653d4b6e6c6e4b53267468656d653d6461726b" data-canonical-src="https://apu5rh8gxk.execute-api.us-east-1.amazonaws.com/default/leetcode-stats?username=KnlnKS&amp;theme=dark" style="max-width: 100%;" width="400">
```

Has broken link [https://camo.githubusercontent.com/1eebccd44222e88e734e4b4972493af998af8fa27f2008244f3e9b90f85497d4/68747470733a2f2f6170753572683867786b2e657865637574652d6170692e75732d656173742d312e616d617a6f6e6177732e636f6d2f64656661756c742f6c656574636f64652d73746174733f757365726e616d653d4b6e6c6e4b53267468656d653d6461726b](https://camo.githubusercontent.com/1eebccd44222e88e734e4b4972493af998af8fa27f2008244f3e9b90f85497d4/68747470733a2f2f6170753572683867786b2e657865637574652d6170692e75732d656173742d312e616d617a6f6e6177732e636f6d2f64656661756c742f6c656574636f64652d73746174733f757365726e616d653d4b6e6c6e4b53267468656d653d6461726b)

**To Reproduce**
1. Go to 'README.md'
2. Scroll down to '46 . [leetcode Stats](https://github.com/KnlnKS/leetcode-stats)'
3. See error

**Expected behavior**
To show image

**Screenshots**
<img width="641" alt="image" src="https://github.com/rzashakeri/beautify-github-profile/assets/108837858/a958f123-8e39-445a-9fca-af5e25f778d8">

**Comment by rzashakeri** [comment]
> **Describe the bug** Image for leetcode stats
> 
> ```
> <img alt="LeetCode Stat Card" src="https://camo.githubusercontent.com/1eebccd44222e88e734e4b4972493af998af8fa27f2008244f3e9b90f85497d4/68747470733a2f2f6170753572683867786b2e657865637574652d6170692e75732d656173742d312e616d617a6f6e6177732e636f6d2f64656661756c742f6c656574636f64652d73746174733f757365726e616d653d4b6e6c6e4b53267468656d653d6461726b" data-canonical-src="https://apu5rh8gxk.execute-api.us-east-1.amazonaws.com/default/leetcode-stats?username=KnlnKS&amp;theme=dark" style="max-width: 100%;" width="400">
> ```
> 
> Has broken link https://camo.githubusercontent.com/1eebccd44222e88e734e4b4972493af998af8fa27f2008244f3e9b90f85497d4/68747470733a2f2f6170753572683867786b2e657865637574652d6170692e75732d656173742d312e616d617a6f6e6177732e636f6d2f64656661756c742f6c656574636f64652d73746174733f757365726e616d653d4b6e6c6e4b53267468656d653d6461726b
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to 'README.md'
> 
>     2. Scroll down to '46 . [leetcode Stats](https://github.com/KnlnKS/leetcode-stats)'
> 
>     3. See error
> 
> 
> **Expected behavior** To show image
> 
> **Screenshots** <img alt="image" width="641" src="https://user-images.githubusercontent.com/108837858/273602096-a958f123-8e39-445a-9fca-af5e25f778d8.png">

Thanks for reporting
fixed
