### ISSUE TITLE
Custom Icon Badges repo

### ISSUE THREAD

**Issue by DenverCoder1** [rzashakeri/beautify-github-profile#9]
Another useful Badges repo you could include is [https://github.com/DenverCoder1/custom-icon-badges](https://github.com/DenverCoder1/custom-icon-badges).

Unlike most badges repos which just support brands from Simple Icons, Custom Icon Badges allows you to GitHub's [Octicons](https://github.com/primer/octicons) or upload your own custom icons to use on badges.

Examples:

[![stars](https://custom-icon-badges.herokuapp.com/github/stars/DenverCoder1/custom-icon-badges?logo=star)](https://github.com/DenverCoder1/custom-icon-badges/stargazers "stars") [![issues](https://custom-icon-badges.herokuapp.com/github/issues-raw/DenverCoder1/custom-icon-badges?logo=issue)](https://github.com/DenverCoder1/custom-icon-badges/issues "issues") [![license](https://custom-icon-badges.herokuapp.com/github/license/denvercoder1/custom-icon-badges?logo=repo)](https://github.com/DenverCoder1/custom-icon-badges/blob/main/LICENSE?rgh-link-date=2021-08-09T18%3A10%3A26Z "license MIT")

![image](https://user-images.githubusercontent.com/20955511/169626857-8baf7db1-cb12-4460-920c-4b5bcb1d9dff.png)

**Comment by rzashakeri** [comment]
hi my friend
thanks for share this tool 💙
i add this good repository ✅
